### ISSUE TITLE
some kind of glitch

### ISSUE THREAD

**Issue by el3ctr0wqw1** [bloodgit/TF2-Dodgeball#4]
so when the round starts if the player jumps the cross-hair flickers up or down randomly , also when approaching walls you cant control the mouse it keeps going mad switching directions

**Comment by el3ctr0wqw1** [comment]
okay i found the solution, just use the previous release (before the latest one) and problem fixed hope this help

**Comment by Nikita-rostov** [comment]
el3ctr0wqw1, what version of the plugin did you install?

**Comment by jawwadbr** [comment]
I know this issue is closed, but what version you used to fix ? I tried 1.4.1, 1.4.3 and that PR Version, the bug still goes.

**Comment by jawwadbr** [comment]
> el3ctr0wqw1, what version of the plugin did you install?

Use 1.4.2 version, for me don't have this bug.
